### ISSUE TITLE
Permissions problem within plugin-manager installr script

### ISSUE THREAD

**Issue by DaveC49** [microelly2/freecad-pluginloader#14]
Hi 
I received the following permissions error when trying to use the self installer script from within FreeCAD

/usr/lib/freecad//Mod/plugins/
Traceback (most recent call last):
  File "/home/david/.FreeCAD/pluginManager_installer.py", line 42, in <module>
    st1()
  File "/home/david/.FreeCAD/pluginManager_installer.py", line 34, in st1
    os.makedirs(directory)
  File "/usr/bin/../lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
<type 'exceptions.OSError'>: (13, 'Permission denied', '/usr/lib/freecad//Mod/plugins/')

OS: Linux Mint 17.2 Rafaela
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.6131 (Git)
Build type: None
Branch: master
Hash: ed037c138ed010d09c8c554c13e06e05518f1bf5
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 6.8.0.oce-0.17

Iam logged in as a normal user not root. It appears that os.py  is not able to request su permissions when needed. 

Installed as per manual installation instructions - no problems. Appears in Menu->View->Panels rather than in Views
Cheers
David

**Comment by 3h600** [comment]
The same here, but when I install it manually, no plugins available to download at all. Actually I have empty table. Linux Mint 17.3
