### ISSUE TITLE
Strange behavior with Screw maker macro

### ISSUE THREAD

**Issue by kkoksvik** [microelly2/freecad-pluginloader#8]
#### When trying to run it:

!fn="/home/kjetil/.FreeCAD/Macros/screw_maker1_7.py";exec open(fn).read()!
fn="/home/kjetil/.FreeCAD/Macros/screw_maker1_7.py";exec open(fn).read()
Traceback (most recent call last):
-->    File "<string>", line 73, in run
-->    File "<string>", line 1, in <module>
-->  IOError: [Errno 2] No such file or directory: '/home/kjetil/.FreeCAD/Macros/screw_maker1_7.py'
#### it fails to run with the following output.

!fn="/home/kjetil/.FreeCAD/Macros/screw_maker1_7.py";exec open(fn).read()!
PySyde is used
fn="/home/kjetil/.FreeCAD/Macros/screw_maker1_7.py";exec open(fn).read()
Traceback (most recent call last):
-->    File "<string>", line 73, in run
-->    File "<string>", line 1, in <module>
-->    File "<string>", line 2887, in <module>
-->    File "<string>", line 2889, in screw
-->  NameError: name 'Ui_ScrewMaker' is not defined

**Comment by microelly2** [comment]
I have a local version of the screw maker macro without this error (dialog comes up) but with an error on another place (no screw generated) . When I have fixed the problem I will publish the new version.

**Comment by kkoksvik** [comment]
If you would give me a list of the modules/macros that work for you I could test them on my system.

**Comment by kkoksvik** [comment]
When I move screw_maker1_7.py file directly under .FreeCAD/Macros i can execute manually from the Macros menu. It creates screws perfectly. I can not run it from the Pluginmanager

**Comment by microelly2** [comment]
I have placed a version screw make macro into the FreeCAD macro project. 
https://github.com/FreeCAD/FreeCAD-macros
Yes there is an other way to hold the window open.

It works now as dock window. I still have a problem to run it with copy and paste 
see:  http://forum.freecadweb.org/viewtopic.php?f=22&t=10966

You have to update FreeCAD-macros 
(and Pluginloader)

Then screw maker should run from the pluginmanager

My idea is to bring the macros step by step to the FreeCAD-macros  git project 
we have:
solid sweep
screw maker

for the sheet metal unfold  there is a workbench by JMG, he has done something last days and I wait until his git is updated - so no activity for the unfold macro needed.
